services:
  # Railgun App
  railgun_app:
    image: railgun:0.0.1
    environment:
      # Comma delimited list of valid access URLS
      RG_URL: 'https://railgun.aigis.dev,https://archive.aigis.dev,http://metis:5174,http://metis:5151,http://127.0.0.1:5151'
    ports:
      - "8888:8888"
    restart: always
    volumes:
      # Mount DB connection secrets to the appropriate location.
      - ./db_secrets:/opt/railgun/config/db_secrets
      # Mount JWT key to the appropriate location
      - ./secrets/auth.secret:/opt/railgun/config/auth.secret
      # Mount file/media location
      - ./files:/opt/railgun/files
    networks:
      - railgun_network
    depends_on:
      stellardb:
        condition: service_healthy

  # Redis
  stellar:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --loglevel warning
    networks:
      - railgun_network

  # Stellar DB
  stellardb:
    image: stellardb:0.0.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: railgun
      POSTGRES_DB: railgun_internal
      PGDATA: /var/lib/postgresql/data  # Default
    restart: always
    volumes:
      - ../deploy/pgdata:/var/lib/postgresql/data
      - ../deploy/db_backups:/opt/db_backups
    networks:
      - railgun_network
    healthcheck:
      test: "pg_isready -U railgun -d railgun_internal"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  railgun_network:
    name: railgun_network